### ISSUE TITLE
Looks like facebook icon is missing for the social icons in the sidebar

### ISSUE THREAD

**Issue by dontpanic** [krisawzm/simply-blog-theme#1]
I added this line to `_font-awesome.scss`, recompiled the sass, and everything seems to work!

```
.#{$fa-css-prefix}-facebook:before { content: $fa-var-facebook; }
```

Looks like only the `fa-facebook-official` was being loaded.

**Comment by kalfheim** [comment]
Any chance you could make a pull request?

**Comment by dontpanic** [comment]
Sure, after the weekend I'll set it up.

**Comment by kalfheim** [comment]
Thanks!
